### PR TITLE
feat(Configurations): Support Client (Runtime) Configurations

### LINKED ISSUE #8: Support Multiple Configurations Sources
This is to support loading configurations from multiple sources. Including (but not limited to):

- Runtime.
- File System.
- Default.

### PR DESCRIPTION
**Pull request by mohnoor94**
### :pencil: Description
- Support passing runtime configurations.
- Get rid of `EnvironmentConfigs` and all related logic.
- Refactor the hierarchy or our configuration to accept configurations from multiple (and mixed) sources, for now, we support Client (Runtime), FileSystem, and a default Fallback provider. A new source could be easily added.
- Expose our `Client` class to the generated SDKs instead of only the `httpClient` which opens a lot of doors to what we can implement and do in the generated codebases.
- "Internalize" a lot of our internal code in the core so that it won't be accessible from our partners (they don't need to, so they should not have access to it).
- Refactor, clean, and document _related_ code.
- Bump up the version to `0.0.2-alpha`.

**BREAKING CHANGE**: `base_url` is replaced by `endpoint` configuration.
**BREAKING CHANGE**: `auth_url` is replaced by `auth_endpoint` configuration.

### :link: Related Issues
Closes #8 

### :link: Related PRs
PR: https://github.com/ExpediaGroup/openworld-sdk-java-generators/pull/5

### CODE REVIEW

**Comment by ayansen** [comment]
@mohnoor94 - what is a runtime configuration?

**Comment by ayansen** [comment]
can you create a separate pr with the refactor and code cleanup?

**Comment by mohnoor94** [comment]
> @mohnoor94 - what is a runtime configuration?

Any (supported) configuration we need to pass as a parameter on runtime.



> can you create a separate pr with the refactor and code cleanup?

I'm always an advocate for this, but I only refactored certain areas of the code that are tightly coupled with my changes. We have some PRs for cleaning in the pipeline for the other - unconnected ones.

**Comment by ayansen** [comment]
> Any (supported) configuration we need to pass as a parameter on runtime.
@mohnoor94 - all configurations should be allowed to pass on runtime, the configuration provider is an add-on class which can be used by the builder to read the configurations from a file/data-source. The Config Class as part of the open pr https://github.com/ExpediaGroup/openworld-sdk-java-core/pull/10, should be leveraged by the sdk-builder, in addition, the builder should have the ability to source the configurations from a provider and override them, I can see how runtime configurations would fit in as an override if the sdk-builder chooses a provider but I think it the code semantics would look different and it wouldn't be coupled with any of the other classes in the sdk

**Review by ayansen — CHANGES_REQUESTED** [review]
Apologies for the comment - this pr needs to be broken down into smaller pr's. I would encourage just having the class to override and its tests in the first pr

**Comment by mohnoor94** [comment]
@ayansen Let's have a meeting to continue our discussion.

**Comment by mohnoor94** [comment]
Split into multiple other PRs. Closing.

**Pull request closed without merging**
